/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as DemoRouteRouteImport } from './routes/demo/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoUtilitiesRouteImport } from './routes/demo/utilities'
import { Route as DemoToggleSwitchRouteImport } from './routes/demo/toggle-switch'
import { Route as DemoTimersRouteImport } from './routes/demo/timers'
import { Route as DemoTimelinesRouteImport } from './routes/demo/timelines'
import { Route as DemoSvgPathDrawRouteImport } from './routes/demo/svg-path-draw'
import { Route as DemoSvgRouteImport } from './routes/demo/svg'
import { Route as DemoSplitTextRouteImport } from './routes/demo/split-text'
import { Route as DemoSpinningCubeRouteImport } from './routes/demo/spinning-cube'
import { Route as DemoScopeRouteImport } from './routes/demo/scope'
import { Route as DemoReorderListRouteImport } from './routes/demo/reorder-list'
import { Route as DemoPlaybackSettingsRouteImport } from './routes/demo/playback-settings'
import { Route as DemoOnscrollRouteImport } from './routes/demo/onscroll'
import { Route as DemoMethodsRouteImport } from './routes/demo/methods'
import { Route as DemoLayoutRouteImport } from './routes/demo/layout'
import { Route as DemoEasingsRouteImport } from './routes/demo/easings'
import { Route as DemoDraggableRouteImport } from './routes/demo/draggable'
import { Route as DemoCounterCountdownRouteImport } from './routes/demo/counter-countdown'
import { Route as DemoCoreFeaturesRouteImport } from './routes/demo/core-features'
import { Route as DemoClippathRevealRouteImport } from './routes/demo/clippath-reveal'
import { Route as DemoCallbacksRouteImport } from './routes/demo/callbacks'
import { Route as DemoAnimatedSliderRouteImport } from './routes/demo/animated-slider'
import { Route as DemoAnimatePresenceRouteImport } from './routes/demo/animate-presence'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRouteRoute = DemoRouteRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoUtilitiesRoute = DemoUtilitiesRouteImport.update({
  id: '/utilities',
  path: '/utilities',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoToggleSwitchRoute = DemoToggleSwitchRouteImport.update({
  id: '/toggle-switch',
  path: '/toggle-switch',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoTimersRoute = DemoTimersRouteImport.update({
  id: '/timers',
  path: '/timers',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoTimelinesRoute = DemoTimelinesRouteImport.update({
  id: '/timelines',
  path: '/timelines',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoSvgPathDrawRoute = DemoSvgPathDrawRouteImport.update({
  id: '/svg-path-draw',
  path: '/svg-path-draw',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoSvgRoute = DemoSvgRouteImport.update({
  id: '/svg',
  path: '/svg',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoSplitTextRoute = DemoSplitTextRouteImport.update({
  id: '/split-text',
  path: '/split-text',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoSpinningCubeRoute = DemoSpinningCubeRouteImport.update({
  id: '/spinning-cube',
  path: '/spinning-cube',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoScopeRoute = DemoScopeRouteImport.update({
  id: '/scope',
  path: '/scope',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoReorderListRoute = DemoReorderListRouteImport.update({
  id: '/reorder-list',
  path: '/reorder-list',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoPlaybackSettingsRoute = DemoPlaybackSettingsRouteImport.update({
  id: '/playback-settings',
  path: '/playback-settings',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoOnscrollRoute = DemoOnscrollRouteImport.update({
  id: '/onscroll',
  path: '/onscroll',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoMethodsRoute = DemoMethodsRouteImport.update({
  id: '/methods',
  path: '/methods',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoLayoutRoute = DemoLayoutRouteImport.update({
  id: '/layout',
  path: '/layout',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoEasingsRoute = DemoEasingsRouteImport.update({
  id: '/easings',
  path: '/easings',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoDraggableRoute = DemoDraggableRouteImport.update({
  id: '/draggable',
  path: '/draggable',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoCounterCountdownRoute = DemoCounterCountdownRouteImport.update({
  id: '/counter-countdown',
  path: '/counter-countdown',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoCoreFeaturesRoute = DemoCoreFeaturesRouteImport.update({
  id: '/core-features',
  path: '/core-features',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoClippathRevealRoute = DemoClippathRevealRouteImport.update({
  id: '/clippath-reveal',
  path: '/clippath-reveal',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoCallbacksRoute = DemoCallbacksRouteImport.update({
  id: '/callbacks',
  path: '/callbacks',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoAnimatedSliderRoute = DemoAnimatedSliderRouteImport.update({
  id: '/animated-slider',
  path: '/animated-slider',
  getParentRoute: () => DemoRouteRoute,
} as any)
const DemoAnimatePresenceRoute = DemoAnimatePresenceRouteImport.update({
  id: '/animate-presence',
  path: '/animate-presence',
  getParentRoute: () => DemoRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteRouteWithChildren
  '/mcp': typeof McpRoute
  '/demo/animate-presence': typeof DemoAnimatePresenceRoute
  '/demo/animated-slider': typeof DemoAnimatedSliderRoute
  '/demo/callbacks': typeof DemoCallbacksRoute
  '/demo/clippath-reveal': typeof DemoClippathRevealRoute
  '/demo/core-features': typeof DemoCoreFeaturesRoute
  '/demo/counter-countdown': typeof DemoCounterCountdownRoute
  '/demo/draggable': typeof DemoDraggableRoute
  '/demo/easings': typeof DemoEasingsRoute
  '/demo/layout': typeof DemoLayoutRoute
  '/demo/methods': typeof DemoMethodsRoute
  '/demo/onscroll': typeof DemoOnscrollRoute
  '/demo/playback-settings': typeof DemoPlaybackSettingsRoute
  '/demo/reorder-list': typeof DemoReorderListRoute
  '/demo/scope': typeof DemoScopeRoute
  '/demo/spinning-cube': typeof DemoSpinningCubeRoute
  '/demo/split-text': typeof DemoSplitTextRoute
  '/demo/svg': typeof DemoSvgRoute
  '/demo/svg-path-draw': typeof DemoSvgPathDrawRoute
  '/demo/timelines': typeof DemoTimelinesRoute
  '/demo/timers': typeof DemoTimersRoute
  '/demo/toggle-switch': typeof DemoToggleSwitchRoute
  '/demo/utilities': typeof DemoUtilitiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteRouteWithChildren
  '/mcp': typeof McpRoute
  '/demo/animate-presence': typeof DemoAnimatePresenceRoute
  '/demo/animated-slider': typeof DemoAnimatedSliderRoute
  '/demo/callbacks': typeof DemoCallbacksRoute
  '/demo/clippath-reveal': typeof DemoClippathRevealRoute
  '/demo/core-features': typeof DemoCoreFeaturesRoute
  '/demo/counter-countdown': typeof DemoCounterCountdownRoute
  '/demo/draggable': typeof DemoDraggableRoute
  '/demo/easings': typeof DemoEasingsRoute
  '/demo/layout': typeof DemoLayoutRoute
  '/demo/methods': typeof DemoMethodsRoute
  '/demo/onscroll': typeof DemoOnscrollRoute
  '/demo/playback-settings': typeof DemoPlaybackSettingsRoute
  '/demo/reorder-list': typeof DemoReorderListRoute
  '/demo/scope': typeof DemoScopeRoute
  '/demo/spinning-cube': typeof DemoSpinningCubeRoute
  '/demo/split-text': typeof DemoSplitTextRoute
  '/demo/svg': typeof DemoSvgRoute
  '/demo/svg-path-draw': typeof DemoSvgPathDrawRoute
  '/demo/timelines': typeof DemoTimelinesRoute
  '/demo/timers': typeof DemoTimersRoute
  '/demo/toggle-switch': typeof DemoToggleSwitchRoute
  '/demo/utilities': typeof DemoUtilitiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteRouteWithChildren
  '/mcp': typeof McpRoute
  '/demo/animate-presence': typeof DemoAnimatePresenceRoute
  '/demo/animated-slider': typeof DemoAnimatedSliderRoute
  '/demo/callbacks': typeof DemoCallbacksRoute
  '/demo/clippath-reveal': typeof DemoClippathRevealRoute
  '/demo/core-features': typeof DemoCoreFeaturesRoute
  '/demo/counter-countdown': typeof DemoCounterCountdownRoute
  '/demo/draggable': typeof DemoDraggableRoute
  '/demo/easings': typeof DemoEasingsRoute
  '/demo/layout': typeof DemoLayoutRoute
  '/demo/methods': typeof DemoMethodsRoute
  '/demo/onscroll': typeof DemoOnscrollRoute
  '/demo/playback-settings': typeof DemoPlaybackSettingsRoute
  '/demo/reorder-list': typeof DemoReorderListRoute
  '/demo/scope': typeof DemoScopeRoute
  '/demo/spinning-cube': typeof DemoSpinningCubeRoute
  '/demo/split-text': typeof DemoSplitTextRoute
  '/demo/svg': typeof DemoSvgRoute
  '/demo/svg-path-draw': typeof DemoSvgPathDrawRoute
  '/demo/timelines': typeof DemoTimelinesRoute
  '/demo/timers': typeof DemoTimersRoute
  '/demo/toggle-switch': typeof DemoToggleSwitchRoute
  '/demo/utilities': typeof DemoUtilitiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/mcp'
    | '/demo/animate-presence'
    | '/demo/animated-slider'
    | '/demo/callbacks'
    | '/demo/clippath-reveal'
    | '/demo/core-features'
    | '/demo/counter-countdown'
    | '/demo/draggable'
    | '/demo/easings'
    | '/demo/layout'
    | '/demo/methods'
    | '/demo/onscroll'
    | '/demo/playback-settings'
    | '/demo/reorder-list'
    | '/demo/scope'
    | '/demo/spinning-cube'
    | '/demo/split-text'
    | '/demo/svg'
    | '/demo/svg-path-draw'
    | '/demo/timelines'
    | '/demo/timers'
    | '/demo/toggle-switch'
    | '/demo/utilities'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/mcp'
    | '/demo/animate-presence'
    | '/demo/animated-slider'
    | '/demo/callbacks'
    | '/demo/clippath-reveal'
    | '/demo/core-features'
    | '/demo/counter-countdown'
    | '/demo/draggable'
    | '/demo/easings'
    | '/demo/layout'
    | '/demo/methods'
    | '/demo/onscroll'
    | '/demo/playback-settings'
    | '/demo/reorder-list'
    | '/demo/scope'
    | '/demo/spinning-cube'
    | '/demo/split-text'
    | '/demo/svg'
    | '/demo/svg-path-draw'
    | '/demo/timelines'
    | '/demo/timers'
    | '/demo/toggle-switch'
    | '/demo/utilities'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/mcp'
    | '/demo/animate-presence'
    | '/demo/animated-slider'
    | '/demo/callbacks'
    | '/demo/clippath-reveal'
    | '/demo/core-features'
    | '/demo/counter-countdown'
    | '/demo/draggable'
    | '/demo/easings'
    | '/demo/layout'
    | '/demo/methods'
    | '/demo/onscroll'
    | '/demo/playback-settings'
    | '/demo/reorder-list'
    | '/demo/scope'
    | '/demo/spinning-cube'
    | '/demo/split-text'
    | '/demo/svg'
    | '/demo/svg-path-draw'
    | '/demo/timelines'
    | '/demo/timers'
    | '/demo/toggle-switch'
    | '/demo/utilities'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRouteRoute: typeof DemoRouteRouteWithChildren
  McpRoute: typeof McpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/utilities': {
      id: '/demo/utilities'
      path: '/utilities'
      fullPath: '/demo/utilities'
      preLoaderRoute: typeof DemoUtilitiesRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/toggle-switch': {
      id: '/demo/toggle-switch'
      path: '/toggle-switch'
      fullPath: '/demo/toggle-switch'
      preLoaderRoute: typeof DemoToggleSwitchRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/timers': {
      id: '/demo/timers'
      path: '/timers'
      fullPath: '/demo/timers'
      preLoaderRoute: typeof DemoTimersRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/timelines': {
      id: '/demo/timelines'
      path: '/timelines'
      fullPath: '/demo/timelines'
      preLoaderRoute: typeof DemoTimelinesRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/svg-path-draw': {
      id: '/demo/svg-path-draw'
      path: '/svg-path-draw'
      fullPath: '/demo/svg-path-draw'
      preLoaderRoute: typeof DemoSvgPathDrawRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/svg': {
      id: '/demo/svg'
      path: '/svg'
      fullPath: '/demo/svg'
      preLoaderRoute: typeof DemoSvgRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/split-text': {
      id: '/demo/split-text'
      path: '/split-text'
      fullPath: '/demo/split-text'
      preLoaderRoute: typeof DemoSplitTextRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/spinning-cube': {
      id: '/demo/spinning-cube'
      path: '/spinning-cube'
      fullPath: '/demo/spinning-cube'
      preLoaderRoute: typeof DemoSpinningCubeRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/scope': {
      id: '/demo/scope'
      path: '/scope'
      fullPath: '/demo/scope'
      preLoaderRoute: typeof DemoScopeRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/reorder-list': {
      id: '/demo/reorder-list'
      path: '/reorder-list'
      fullPath: '/demo/reorder-list'
      preLoaderRoute: typeof DemoReorderListRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/playback-settings': {
      id: '/demo/playback-settings'
      path: '/playback-settings'
      fullPath: '/demo/playback-settings'
      preLoaderRoute: typeof DemoPlaybackSettingsRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/onscroll': {
      id: '/demo/onscroll'
      path: '/onscroll'
      fullPath: '/demo/onscroll'
      preLoaderRoute: typeof DemoOnscrollRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/methods': {
      id: '/demo/methods'
      path: '/methods'
      fullPath: '/demo/methods'
      preLoaderRoute: typeof DemoMethodsRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/layout': {
      id: '/demo/layout'
      path: '/layout'
      fullPath: '/demo/layout'
      preLoaderRoute: typeof DemoLayoutRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/easings': {
      id: '/demo/easings'
      path: '/easings'
      fullPath: '/demo/easings'
      preLoaderRoute: typeof DemoEasingsRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/draggable': {
      id: '/demo/draggable'
      path: '/draggable'
      fullPath: '/demo/draggable'
      preLoaderRoute: typeof DemoDraggableRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/counter-countdown': {
      id: '/demo/counter-countdown'
      path: '/counter-countdown'
      fullPath: '/demo/counter-countdown'
      preLoaderRoute: typeof DemoCounterCountdownRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/core-features': {
      id: '/demo/core-features'
      path: '/core-features'
      fullPath: '/demo/core-features'
      preLoaderRoute: typeof DemoCoreFeaturesRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/clippath-reveal': {
      id: '/demo/clippath-reveal'
      path: '/clippath-reveal'
      fullPath: '/demo/clippath-reveal'
      preLoaderRoute: typeof DemoClippathRevealRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/callbacks': {
      id: '/demo/callbacks'
      path: '/callbacks'
      fullPath: '/demo/callbacks'
      preLoaderRoute: typeof DemoCallbacksRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/animated-slider': {
      id: '/demo/animated-slider'
      path: '/animated-slider'
      fullPath: '/demo/animated-slider'
      preLoaderRoute: typeof DemoAnimatedSliderRouteImport
      parentRoute: typeof DemoRouteRoute
    }
    '/demo/animate-presence': {
      id: '/demo/animate-presence'
      path: '/animate-presence'
      fullPath: '/demo/animate-presence'
      preLoaderRoute: typeof DemoAnimatePresenceRouteImport
      parentRoute: typeof DemoRouteRoute
    }
  }
}

interface DemoRouteRouteChildren {
  DemoAnimatePresenceRoute: typeof DemoAnimatePresenceRoute
  DemoAnimatedSliderRoute: typeof DemoAnimatedSliderRoute
  DemoCallbacksRoute: typeof DemoCallbacksRoute
  DemoClippathRevealRoute: typeof DemoClippathRevealRoute
  DemoCoreFeaturesRoute: typeof DemoCoreFeaturesRoute
  DemoCounterCountdownRoute: typeof DemoCounterCountdownRoute
  DemoDraggableRoute: typeof DemoDraggableRoute
  DemoEasingsRoute: typeof DemoEasingsRoute
  DemoLayoutRoute: typeof DemoLayoutRoute
  DemoMethodsRoute: typeof DemoMethodsRoute
  DemoOnscrollRoute: typeof DemoOnscrollRoute
  DemoPlaybackSettingsRoute: typeof DemoPlaybackSettingsRoute
  DemoReorderListRoute: typeof DemoReorderListRoute
  DemoScopeRoute: typeof DemoScopeRoute
  DemoSpinningCubeRoute: typeof DemoSpinningCubeRoute
  DemoSplitTextRoute: typeof DemoSplitTextRoute
  DemoSvgRoute: typeof DemoSvgRoute
  DemoSvgPathDrawRoute: typeof DemoSvgPathDrawRoute
  DemoTimelinesRoute: typeof DemoTimelinesRoute
  DemoTimersRoute: typeof DemoTimersRoute
  DemoToggleSwitchRoute: typeof DemoToggleSwitchRoute
  DemoUtilitiesRoute: typeof DemoUtilitiesRoute
}

const DemoRouteRouteChildren: DemoRouteRouteChildren = {
  DemoAnimatePresenceRoute: DemoAnimatePresenceRoute,
  DemoAnimatedSliderRoute: DemoAnimatedSliderRoute,
  DemoCallbacksRoute: DemoCallbacksRoute,
  DemoClippathRevealRoute: DemoClippathRevealRoute,
  DemoCoreFeaturesRoute: DemoCoreFeaturesRoute,
  DemoCounterCountdownRoute: DemoCounterCountdownRoute,
  DemoDraggableRoute: DemoDraggableRoute,
  DemoEasingsRoute: DemoEasingsRoute,
  DemoLayoutRoute: DemoLayoutRoute,
  DemoMethodsRoute: DemoMethodsRoute,
  DemoOnscrollRoute: DemoOnscrollRoute,
  DemoPlaybackSettingsRoute: DemoPlaybackSettingsRoute,
  DemoReorderListRoute: DemoReorderListRoute,
  DemoScopeRoute: DemoScopeRoute,
  DemoSpinningCubeRoute: DemoSpinningCubeRoute,
  DemoSplitTextRoute: DemoSplitTextRoute,
  DemoSvgRoute: DemoSvgRoute,
  DemoSvgPathDrawRoute: DemoSvgPathDrawRoute,
  DemoTimelinesRoute: DemoTimelinesRoute,
  DemoTimersRoute: DemoTimersRoute,
  DemoToggleSwitchRoute: DemoToggleSwitchRoute,
  DemoUtilitiesRoute: DemoUtilitiesRoute,
}

const DemoRouteRouteWithChildren = DemoRouteRoute._addFileChildren(
  DemoRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRouteRoute: DemoRouteRouteWithChildren,
  McpRoute: McpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
